-- 条目21优化：政策卡收益显示（EPC）扩展类型的自定义措辞（无参纯文本 tag，Lua .. 拼接组装行）
-- 对象名/类别名/时代/资源/能力官方名走原版 LOC tag 自动本地化，此处只补引擎自造短语
INSERT OR REPLACE INTO LocalizedText (Tag, Language, Text) VALUES
	('LOC_MPT_EPC_PER_TURN',			'zh_Hans_CN',	'/回合'),
	('LOC_MPT_EPC_PRODUCTION',			'zh_Hans_CN',	'生产力'),
	('LOC_MPT_EPC_PROJECTS',			'zh_Hans_CN',	'项目'),
	('LOC_MPT_EPC_SPACE_PROJECTS',		'zh_Hans_CN',	'太空项目'),
	('LOC_MPT_EPC_ALL_UNITS',			'zh_Hans_CN',	'全单位'),
	('LOC_MPT_EPC_WONDER',				'zh_Hans_CN',	'奇观'),
	('LOC_MPT_EPC_PURCHASE',			'zh_Hans_CN',	'购买费用'),
	('LOC_MPT_EPC_UPGRADE_COST',		'zh_Hans_CN',	'单位升级金币'),
	('LOC_MPT_EPC_UPGRADE_RES',			'zh_Hans_CN',	'单位升级资源'),
	('LOC_MPT_EPC_PLOT_COST',			'zh_Hans_CN',	'购地费用'),
	('LOC_MPT_EPC_CS_TRADE',			'zh_Hans_CN',	'对城邦商路'),
	('LOC_MPT_EPC_DISTRICT_GOLD',		'zh_Hans_CN',	'新建街区获金(依魅力)'),
	('LOC_MPT_EPC_POST_COMBAT',			'zh_Hans_CN',	'击杀战利'),
	('LOC_MPT_EPC_PLUNDER',				'zh_Hans_CN',	'劫掠收益'),
	('LOC_MPT_EPC_TOURISM',				'zh_Hans_CN',	'商路旅游业绩'),
	('LOC_MPT_EPC_TOURISM_IN',			'zh_Hans_CN',	'外来旅游业绩'),
	('LOC_MPT_EPC_ROCKBAND',			'zh_Hans_CN',	'乐队演出旅游'),
	('LOC_MPT_EPC_POWER_FREE',			'zh_Hans_CN',	'每城免费电力'),
	('LOC_MPT_EPC_RESOURCE_FREE',		'zh_Hans_CN',	'每城免费资源'),
	('LOC_MPT_EPC_INFLUENCE',			'zh_Hans_CN',	'影响力点'),
	('LOC_MPT_EPC_ENVOY_FIRST',			'zh_Hans_CN',	'首个使者 ×2'),
	('LOC_MPT_EPC_ENVOY_RIVAL',			'zh_Hans_CN',	'对异政体城邦使者 ×2'),
	('LOC_MPT_EPC_ALLIANCE',			'zh_Hans_CN',	'联盟点'),
	('LOC_MPT_EPC_INQ_CHARGES',			'zh_Hans_CN',	'审判官剩余次数'),
	('LOC_MPT_EPC_BUILD_CHARGES',		'zh_Hans_CN',	'建造者次数'),
	('LOC_MPT_EPC_UNIT_MOVEMENT',		'zh_Hans_CN',	'单位移动'),
	('LOC_MPT_EPC_MOVEMENT_ENEMY',		'zh_Hans_CN',	'敌境起始移动'),
	('LOC_MPT_EPC_MOVEMENT_FRIENDLY',	'zh_Hans_CN',	'友境起始移动'),
	('LOC_MPT_EPC_XP',					'zh_Hans_CN',	'经验获取'),
	('LOC_MPT_EPC_BARBARIAN',			'zh_Hans_CN',	'对蛮族战力'),
	('LOC_MPT_EPC_OUTER_DEFENSE',		'zh_Hans_CN',	'城市外部防御'),
	('LOC_MPT_EPC_RANGED_STRIKE',		'zh_Hans_CN',	'城市远程打击'),
	('LOC_MPT_EPC_DAMAGE_REDUCTION',	'zh_Hans_CN',	'受损战力减免'),
	('LOC_MPT_EPC_COMBAT_STRENGTH',		'zh_Hans_CN',	'单位战力'),
	('LOC_MPT_EPC_WAR_WEARINESS',		'zh_Hans_CN',	'厌战积累'),
	('LOC_MPT_EPC_DOMESTIC',			'zh_Hans_CN',	'(本土)'),
	('LOC_MPT_EPC_SPY_OFF',				'zh_Hans_CN',	'间谍行动等级'),
	('LOC_MPT_EPC_SPY_DEF',				'zh_Hans_CN',	'反间谍等级'),
	('LOC_MPT_EPC_STEAL_BOOST',			'zh_Hans_CN',	'窃取科技附赠完整加速'),
	('LOC_MPT_EPC_SPY_TIME',			'zh_Hans_CN',	'间谍行动耗时'),
	('LOC_MPT_EPC_ABILITY',				'zh_Hans_CN',	'获得能力:'),
	('LOC_MPT_EPC_NO_PROMO_LIMIT',		'zh_Hans_CN',	'晋升无限制'),
	('LOC_MPT_EPC_NO_HEAL_FOREIGN',		'zh_Hans_CN',	'禁止在敌境治疗'),
	('LOC_MPT_EPC_NO_HEAL',				'zh_Hans_CN',	'禁止治疗'),
	('LOC_MPT_EPC_NO_INFLUENCE',		'zh_Hans_CN',	'禁止获得影响力'),
	('LOC_MPT_EPC_NO_SETTLING',			'zh_Hans_CN',	'禁止建立新城市'),
	('LOC_MPT_EPC_BLOCK_ENTRY',			'zh_Hans_CN',	'禁止进入'),
	('LOC_MPT_EPC_BUILD_DISABLED',		'zh_Hans_CN',	'禁止建造'),
	('LOC_MPT_EPC_OPEN_BORDERS',		'zh_Hans_CN',	'对城邦开放边境'),
	('LOC_MPT_EPC_NO_GRIEVANCE_DECAY',	'zh_Hans_CN',	'不满不再衰减'),
	('LOC_MPT_EPC_RESOLUTION',			'zh_Hans_CN',	'世界议会决议'),
	('LOC_MPT_EPC_PER_BUILDING',		'zh_Hans_CN',	'每座'),
	-- GRANT_ABILITY 官方无文本的隐藏能力（10 个中 9 个官方 UnitAbilities.Name 为 NULL，
	-- 优先级：官方 Name → 此处 → 能力 ID 原文）
	('LOC_MPT_EPC_ABILITY_FASCISM_LEGACY_ATTACK_BUFF',			'zh_Hans_CN',	'法西斯传承: 攻击加成'),
	('LOC_MPT_EPC_ABILITY_OLIGARCHY_LEGACY_MELEE_BUFF',			'zh_Hans_CN',	'寡头传承: 近战加成'),
	('LOC_MPT_EPC_ABILITY_THEOCRACY_LEGACY_RELIGIOUS_BUFF',		'zh_Hans_CN',	'神权传承: 宗教单位加成'),
	('LOC_MPT_EPC_ABILITY_RELIGIOUS_ORDERS_BUFF',				'zh_Hans_CN',	'宗教订单: 信条单位战力加成'),
	('LOC_MPT_EPC_ABILITY_FINEST_HOUR_FRIENDLY_TERRITORY',		'zh_Hans_CN',	'高光时刻: 本土境内加成'),
	('LOC_MPT_EPC_ABILITY_GLOBAL_COALITION_FRIENDLY_TERRITORY',	'zh_Hans_CN',	'全球联合: 本土境内加成'),
	('LOC_MPT_EPC_ABILITY_INQUISITION_FRIENDLY_TERRITORY_BONUS','zh_Hans_CN',	'审判: 本土境内加成'),
	('LOC_MPT_EPC_ABILITY_TWILIGHT_VALOR_ATTACK_BONUS',			'zh_Hans_CN',	'暮光勇气: 攻击加成'),
	('LOC_MPT_EPC_ABILITY_CYBER_WARFARE_COMBAT_BONUS',			'zh_Hans_CN',	'网络战: 战力加成');
