-- Entry 21 optimization: custom phrases for extended policy card effect lines (no-arg tags, Lua .. concatenation)
-- Object names / classes / eras / resources / abilities use vanilla LOC tags; only engine-invented phrases live here
INSERT OR REPLACE INTO LocalizedText (Tag, Language, Text) VALUES
	('LOC_MPT_EPC_PER_TURN',			'en_US',	' per turn'),
	('LOC_MPT_EPC_PRODUCTION',			'en_US',	' Production'),
	('LOC_MPT_EPC_PROJECTS',			'en_US',	'projects'),
	('LOC_MPT_EPC_SPACE_PROJECTS',		'en_US',	'Space Race projects'),
	('LOC_MPT_EPC_ALL_UNITS',			'en_US',	'all units'),
	('LOC_MPT_EPC_WONDER',				'en_US',	'Wonder'),
	('LOC_MPT_EPC_PURCHASE',			'en_US',	' purchase cost'),
	('LOC_MPT_EPC_UPGRADE_COST',		'en_US',	'unit upgrade gold'),
	('LOC_MPT_EPC_UPGRADE_RES',			'en_US',	'unit upgrade resources'),
	('LOC_MPT_EPC_PLOT_COST',			'en_US',	'plot purchase cost'),
	('LOC_MPT_EPC_CS_TRADE',			'en_US',	'trade with city-states'),
	('LOC_MPT_EPC_DISTRICT_GOLD',		'en_US',	'Gold from new districts (by Appeal)'),
	('LOC_MPT_EPC_POST_COMBAT',			'en_US',	'Post-combat'),
	('LOC_MPT_EPC_PLUNDER',				'en_US',	'Plunder yields'),
	('LOC_MPT_EPC_TOURISM',				'en_US',	'trade route Tourism'),
	('LOC_MPT_EPC_TOURISM_IN',			'en_US',	'incoming Tourism'),
	('LOC_MPT_EPC_ROCKBAND',			'en_US',	'Rock Band concert Tourism'),
	('LOC_MPT_EPC_POWER_FREE',			'en_US',	'free Power per city'),
	('LOC_MPT_EPC_RESOURCE_FREE',		'en_US',	'free resource per city'),
	('LOC_MPT_EPC_INFLUENCE',			'en_US',	'influence points'),
	('LOC_MPT_EPC_ENVOY_FIRST',			'en_US',	'Double first envoy'),
	('LOC_MPT_EPC_ENVOY_RIVAL',			'en_US',	'Double envoys to city-states with rival governments'),
	('LOC_MPT_EPC_ALLIANCE',			'en_US',	'alliance points'),
	('LOC_MPT_EPC_INQ_CHARGES',			'en_US',	'Inquisitor charges'),
	('LOC_MPT_EPC_BUILD_CHARGES',		'en_US',	'builder charges'),
	('LOC_MPT_EPC_UNIT_MOVEMENT',		'en_US',	'unit movement'),
	('LOC_MPT_EPC_MOVEMENT_ENEMY',		'en_US',	'starting moves in enemy territory'),
	('LOC_MPT_EPC_MOVEMENT_FRIENDLY',	'en_US',	'starting moves in friendly territory'),
	('LOC_MPT_EPC_XP',					'en_US',	'XP gained'),
	('LOC_MPT_EPC_BARBARIAN',			'en_US',	'vs. Barbarians'),
	('LOC_MPT_EPC_OUTER_DEFENSE',		'en_US',	'city outer defense'),
	('LOC_MPT_EPC_RANGED_STRIKE',		'en_US',	'city ranged strike'),
	('LOC_MPT_EPC_DAMAGE_REDUCTION',	'en_US',	'strength loss from damage'),
	('LOC_MPT_EPC_COMBAT_STRENGTH',		'en_US',	'unit combat strength'),
	('LOC_MPT_EPC_WAR_WEARINESS',		'en_US',	'war weariness'),
	('LOC_MPT_EPC_DOMESTIC',			'en_US',	'(domestic)'),
	('LOC_MPT_EPC_SPY_OFF',				'en_US',	'offensive spy ops level'),
	('LOC_MPT_EPC_SPY_DEF',				'en_US',	'counter-spy level'),
	('LOC_MPT_EPC_STEAL_BOOST',			'en_US',	'Stolen techs give full boosts'),
	('LOC_MPT_EPC_SPY_TIME',			'en_US',	'spy operation time'),
	('LOC_MPT_EPC_ABILITY',				'en_US',	'Ability: '),
	('LOC_MPT_EPC_NO_PROMO_LIMIT',		'en_US',	': unlimited promotions'),
	('LOC_MPT_EPC_NO_HEAL_FOREIGN',		'en_US',	'No healing in enemy territory'),
	('LOC_MPT_EPC_NO_HEAL',				'en_US',	'No healing'),
	('LOC_MPT_EPC_NO_INFLUENCE',		'en_US',	'No influence points'),
	('LOC_MPT_EPC_NO_SETTLING',			'en_US',	'Cannot found cities'),
	('LOC_MPT_EPC_BLOCK_ENTRY',			'en_US',	'Cannot enter'),
	('LOC_MPT_EPC_BUILD_DISABLED',		'en_US',	'Cannot build'),
	('LOC_MPT_EPC_OPEN_BORDERS',		'en_US',	'Open borders with city-states'),
	('LOC_MPT_EPC_NO_GRIEVANCE_DECAY',	'en_US',	'Grievances do not decay'),
	('LOC_MPT_EPC_RESOLUTION',			'en_US',	'world resolution'),
	('LOC_MPT_EPC_PER_BUILDING',		'en_US',	'per '),
	-- GRANT_ABILITY hidden abilities with no vanilla text (9 of 10 have NULL UnitAbilities.Name;
	-- priority: vanilla Name -> these -> raw ability id)
	('LOC_MPT_EPC_ABILITY_FASCISM_LEGACY_ATTACK_BUFF',			'en_US',	'Fascism Legacy: attack bonus'),
	('LOC_MPT_EPC_ABILITY_OLIGARCHY_LEGACY_MELEE_BUFF',			'en_US',	'Oligarchy Legacy: melee bonus'),
	('LOC_MPT_EPC_ABILITY_THEOCRACY_LEGACY_RELIGIOUS_BUFF',		'en_US',	'Theocracy Legacy: religious units bonus'),
	('LOC_MPT_EPC_ABILITY_RELIGIOUS_ORDERS_BUFF',				'en_US',	'Religious Orders: combat strength for units of your religion'),
	('LOC_MPT_EPC_ABILITY_FINEST_HOUR_FRIENDLY_TERRITORY',		'en_US',	'Finest Hour: bonus in friendly territory'),
	('LOC_MPT_EPC_ABILITY_GLOBAL_COALITION_FRIENDLY_TERRITORY',	'en_US',	'Global Coalition: bonus in friendly territory'),
	('LOC_MPT_EPC_ABILITY_INQUISITION_FRIENDLY_TERRITORY_BONUS','en_US',	'Inquisition: bonus in friendly territory'),
	('LOC_MPT_EPC_ABILITY_TWILIGHT_VALOR_ATTACK_BONUS',			'en_US',	'Twilight Valor: attack bonus'),
	('LOC_MPT_EPC_ABILITY_CYBER_WARFARE_COMBAT_BONUS',			'en_US',	'Cyber Warfare: combat bonus');
